#!/usr/bin/env bb

;; File convergence plugin for mu.
;;
;; Converges files to a desired state: write content, set permissions,
;; create symlinks, or delete files. Designed to consume desired-state
;; targets generated by pudl (or written by hand).
;;
;; Config options:
;;   path                - destination file path (required, except in capture mode)
;;   source              - source file to copy (mutually exclusive with content)
;;   content             - literal content to write (mutually exclusive with source)
;;   mode                - file permissions as octal string (e.g. "0644", default: "0644")
;;   symlink             - create a symlink to this target (mutually exclusive with source/content)
;;   absent              - if true, ensure the file does not exist (default: false)
;;   owner               - file owner (optional, requires privilege)
;;   group               - file group (optional, requires privilege)
;;   sealed_output_files - capture mode: map sealed_output NAME -> absolute
;;                         local path. The action copies each path to
;;                         $MU_SEALED_OUT_DIR/NAME (0600) so the runner
;;                         routes the bytes through store_secret. Used to
;;                         capture an externally generated secret artifact
;;                         (openssl-generated key, downloaded credential,
;;                         etc.) into the configured secret backend.
;;                         Mutually exclusive with path/content/source/etc.

(require '[cheshire.core :as json]
         '[clojure.string :as str])

(defn handle-discover []
  {"name"             "file"
   "version"          "0.2.0"
   "protocol_version" 1
   "description"      "Manage local files: copy, template, create, symlink, or remove"
   "consumes"         ["source:any"]
   "produces"         ["file"]
   "config_schema"    {"path"                {"type" "string"  "description" "Destination path on the local filesystem"}
                       "source"              {"type" "string"  "description" "Source file to copy from"}
                       "content"             {"type" "string"  "description" "Inline content to write (alternative to source)"}
                       "mode"                {"type" "string"  "default" "0644" "description" "File permission mode"}
                       "symlink"             {"type" "string"  "description" "Create a symlink pointing to this path"}
                       "absent"              {"type" "boolean" "default" false "description" "Ensure the file does not exist"}
                       "owner"               {"type" "string"  "description" "File owner (user name or UID)"}
                       "group"               {"type" "string"  "description" "File group (group name or GID)"}
                       "sealed_output_files" {"type" "object"  "description" "Map of sealed output names to file paths"}}})

(defn target-short-name [target-name]
  (last (str/split target-name #"[:/]")))

(defn plan-absent [config path short]
  ;; Ensure file does not exist.
  {"actions"
   [{"id"         "remove"
     "command"    ["sh" "-c" (str "rm -f '" path "'")]
     "inputs"     {}
     "outputs"    []
     "depends_on" []
     "env"        {}
     "network"    false}]
   "declared_outputs" {}})

(defn plan-symlink [config path target short]
  ;; Create or update a symlink.
  {"actions"
   [{"id"         "symlink"
     "command"    ["sh" "-c" (str "mkdir -p \"$(dirname '" path "')\" && "
                                  "ln -sfn '" target "' '" path "'")]
     "inputs"     {}
     "outputs"    [path]
     "depends_on" []
     "env"        {}
     "network"    false}]
   "declared_outputs" {"file" path}})

(defn plan-write-content [config path content mode short]
  ;; Write literal content to file.
  (let [actions
        [{"id"         "write"
          "command"    ["sh" "-c" (str "mkdir -p \"$(dirname '" path "')\" && "
                                      "cat > '" path "' <<'__MU_EOF__'\n"
                                      content
                                      "\n__MU_EOF__")]
          "inputs"     {}
          "outputs"    [path]
          "depends_on" []
          "env"        {}
          "network"    false}
         {"id"         "chmod"
          "command"    ["chmod" mode path]
          "inputs"     {}
          "outputs"    []
          "depends_on" ["write"]
          "env"        {}
          "network"    false}]
        actions (cond-> actions
                  (get config "owner")
                  (conj {"id"         "chown"
                         "command"    ["chown"
                                      (str (get config "owner")
                                           (when-let [g (get config "group")] (str ":" g)))
                                      path]
                         "inputs"     {}
                         "outputs"    []
                         "depends_on" ["write"]
                         "env"        {}
                         "network"    false}))]
    {"actions"          actions
     "declared_outputs" {"file" path}}))

(defn plan-copy-source [config path source mode short sources]
  ;; Copy a source file to destination.
  (let [actions
        [{"id"         "copy"
          "command"    ["sh" "-c" (str "mkdir -p \"$(dirname '" path "')\" && "
                                      "cp '" source "' '" path "'")]
          "inputs"     {source source}
          "outputs"    [path]
          "depends_on" []
          "env"        {}
          "network"    false}
         {"id"         "chmod"
          "command"    ["chmod" mode path]
          "inputs"     {}
          "outputs"    []
          "depends_on" ["copy"]
          "env"        {}
          "network"    false}]
        actions (cond-> actions
                  (get config "owner")
                  (conj {"id"         "chown"
                         "command"    ["chown"
                                      (str (get config "owner")
                                           (when-let [g (get config "group")] (str ":" g)))
                                      path]
                         "inputs"     {}
                         "outputs"    []
                         "depends_on" ["copy"]
                         "env"        {}
                         "network"    false}))]
    {"actions"          actions
     "declared_outputs" {"file" path}}))

(defn shell-quote
  "Single-quote a string for safe inclusion in a bash command."
  [s]
  (str "'" (str/replace (str s) "'" "'\\''") "'"))

(defn plan-capture
  "Capture mode: copy each local path -> $MU_SEALED_OUT_DIR/NAME (0600).
   The action carries the target's sealed_outputs / sealed_output_modes
   so the runner stores the bytes via the configured provider."
  [target sealed-out sealed-out-modes sealed-files]
  (let [pairs   (sort-by key sealed-files)
        cmd     (str "set -eu\n"
                     "if [ -z \"${MU_SEALED_OUT_DIR:-}\" ]; then\n"
                     "  echo 'file: capture mode requires MU_SEALED_OUT_DIR' >&2\n"
                     "  exit 1\n"
                     "fi\n"
                     (str/join
                      (for [[name src] pairs]
                        (str "cp " (shell-quote src) " "
                             "\"$MU_SEALED_OUT_DIR/" name "\"\n"
                             "chmod 600 \"$MU_SEALED_OUT_DIR/" name "\"\n"))))
        action  (cond-> {"id"             "capture"
                         "command"        ["bash" "-c" cmd]
                         "inputs"         {}
                         "outputs"        []
                         "depends_on"     []
                         "env"            {}
                         "network"        false
                         "sealed_outputs" sealed-out}
                  (seq sealed-out-modes) (assoc "sealed_output_modes" sealed-out-modes))]
    {"actions"          [action]
     "declared_outputs" {}}))

(defn handle-plan [req]
  (let [target           (get req "target")
        tgt-name         (get target "name")
        sources          (get target "sources" [])
        config           (get target "config" {})
        short            (target-short-name tgt-name)
        path             (get config "path")
        mode             (get config "mode" "0644")
        sealed-out       (get target "sealed_outputs" {})
        sealed-out-modes (get target "sealed_output_modes" {})
        sealed-files     (get config "sealed_output_files" {})
        capture?         (or (seq sealed-out) (seq sealed-files))]

    (cond
      ;; Capture mode: validate keys match and emit the capture plan.
      capture?
      (let [out-keys  (set (keys sealed-out))
            file-keys (set (keys sealed-files))]
        (cond
          (not= out-keys file-keys)
          {"error" (str "file: sealed_outputs keys " out-keys
                        " must match config.sealed_output_files keys " file-keys)}
          (or path (get config "content") (get config "source")
              (get config "symlink") (get config "absent" false))
          {"error" "file: capture mode (sealed_output_files) is mutually exclusive with path/content/source/symlink/absent"}
          :else
          (plan-capture target sealed-out sealed-out-modes sealed-files)))

      (not path)
      (throw (ex-info "file plugin requires \"path\" in config" {}))

      (get config "absent" false)
      (plan-absent config path short)

      (get config "symlink")
      (plan-symlink config path (get config "symlink") short)

      (get config "content")
      (plan-write-content config path (get config "content") mode short)

      (get config "source")
      (plan-copy-source config path (get config "source") mode short sources)

      ;; If a source file is listed in sources, copy the first one.
      (seq sources)
      (plan-copy-source config path (first sources) mode short sources)

      :else
      {"error" "file plugin requires one of: content, source, symlink, absent, or sealed_output_files"})))

(defn handle-request [req]
  (case (get req "method")
    "discover" (handle-discover)
    "plan"     (handle-plan req)
    {"error" (str "unknown method: " (get req "method"))}))

;; Main NDJSON loop
(loop []
  (when-let [line (read-line)]
    (let [req  (json/parse-string line)
          resp (handle-request req)]
      (println (json/generate-string resp))
      (flush)
      (recur))))
