// #PluginConfig: generated by `mu migrate` from mu.json.
package mu

plugin: {
	entrypoint: "plugin.bb"
	toolchain:  "bb"
	files: ["plugin.bb", "gather.sh"]
	guide: "GUIDE.md"
}
targets: [{
	target:    "build"
	toolchain: "shell"
	sources: ["plugin.bb", "gather.sh"]
	config: {
		command: ["true"]
		impure: false
	}
}]
