// #PluginConfig: generated by `mu migrate` from mu.json.
package mu

plugin: {
	entrypoint: "plugin.bb"
	toolchain:  "bb"
	files: ["plugin.bb", "pudl.cue"]
	guide: "GUIDE.md"
	schemas: [{
		module:  "mu/aws"
		version: "v1"
		path:    "schemas/mu/aws"
	}]
}
targets: [{
	target:    "build"
	toolchain: "shell"
	sources: ["plugin.bb"]
	config: {
		command: ["true"]
		impure: false
	}
}]
